name: Common - Mirror to Epitech Repository
on:
  push:
    branches:
      - dev
      - main
      - web/dev
      - mobile/dev

env:
  DEST_REPO: git@github.com:EpitechPromo2027/B-DEV-500-TLS-5-1-area-theo.bary.git
  SRC_REPO: git@github.com:RotClub/AREA.git

jobs:
    mirror-push:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Extract branches name
          id: get_tag
          run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

        - name: Mirror to Epitech Repository
          uses: wei/git-sync@v3
          with:
            source_repo: ${{ env.SRC_REPO }}
            source_branch: ${{ env.BRANCH_NAME }}
            destination_repo: ${{ env.DEST_REPO }}
            destination_branch: ${{ env.BRANCH_NAME }}
            ssh_private_key: ${{ secrets.EPITECH_SSH_KEY }}