name: Mobile - Build Android Package
on:
  push:
    branches:
      - dev
      - mobile/dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        run: |
          apk update
          apk add openjdk21

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Set Gradle properties
        run: |
          echo "org.gradle.jvmargs=-Xmx4096m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8" >> gradle.properties
        working-directory: "./mobile"

      - name: Run Android Unit Tests
        run: ./gradlew testDebugUnitTest
        working-directory: "./mobile"

      - name: Build APK
        run: ./gradlew assembleRelease
        working-directory: "./mobile"

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          draft: false
          prerelease: false
          repo: ${{ github.repositoryUrl }}
