# Trigger on tag creation and manual dispatch
name: Mobile - Build iOS Debug Package
on:
  push:
    tags:
      - '*.*.*.dev'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v1
        with:
          java-version: 22

      - name: Set up Kotlin and Gradle environment
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: 'wrapper'
          wrapper-directory: "./mobile"
          build-root-directory: "./mobile"

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build iOS framework (KMM)
        run: ./gradlew embedAndSignAppleFrameworkForXcode
        working-directory: "./mobile"

      - name: Build iOS App
        run: xcodebuild -workspace ios-app.xcworkspace -scheme ios-app -sdk iphoneos -configuration Release
        working-directory: "./mobile"

      - name: Archive iOS App
        run: xcodebuild -workspace ios-app.xcworkspace -scheme ios-app -sdk iphoneos -configuration Release archive -archivePath $PWD/build/ios-app.xcarchive
        working-directory: "./mobile"

      - name: Export IPA
        run: xcodebuild -exportArchive -archivePath $PWD/build/ios-app.xcarchive -exportPath $PWD/build/ios-app.ipa -exportOptionsPlist ios-app/ExportOptions.plist
        working-directory: "./mobile"

      - name: Upload iOS Package
        uses: actions/upload-artifact@v4
        with:
          name: iosPackage
          path: mobile/build/xcode-frameworks
          retention-days: 1

  push:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Step 6: Checkout code for the push job
      - name: Checkout
        uses: actions/checkout@v4

      # Step 7: Download the iOS package artifact created during the build step
      - name: Download iOS package
        uses: actions/download-artifact@v4
        with:
          name: iosPackage
          path: iosPackage

      # Step 8: Publish the iOS package to the GitHub repository
      # You may want to push it as a release or attach it to a specific tag
      - name: Create a new release
        uses: softprops/action-gh-release@v1
        with:
          files: iosPackage/  # Path to your iOS package/framework directory
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
