name: Mobile - Build & Publish pre-release
on:
  push:
    tags:
      - '*.*.*.dev'
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Set Gradle properties
        run: |
          echo "org.gradle.jvmargs=-Xmx4096m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8" >> gradle.properties
        working-directory: "./mobile"

      - name: Run Android Unit Tests
        run: ./gradlew testDebugUnitTest
        working-directory: "./mobile"

      - name: Build APK
        run: ./gradlew assembleDebug
        working-directory: "./mobile"

      - name: Upload APK Package
        uses: actions/upload-artifact@v4
        with:
          name: apkPackage
          path: "./mobile/composeApp/build/outputs/apk/debug/composeApp-debug.apk"
          retention-days: 1
          if-no-files-found: 'error'

  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v1
        with:
          java-version: 22

      - name: Set up Kotlin and Gradle environment
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: 'wrapper'
          wrapper-directory: "./mobile"
          build-root-directory: "./mobile"

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build iOS framework (KMM)
        run: ./gradlew embedAndSignAppleFrameworkForXcode
        working-directory: "./mobile"

      - name: Build iOS App
        run: xcodebuild -workspace ios-app.xcworkspace -scheme ios-app -sdk iphoneos -configuration Release
        working-directory: "./mobile"

      - name: Archive iOS App
        run: xcodebuild -workspace ios-app.xcworkspace -scheme ios-app -sdk iphoneos -configuration Release archive -archivePath $PWD/build/ios-app.xcarchive
        working-directory: "./mobile"

      - name: Export IPA
        run: xcodebuild -exportArchive -archivePath $PWD/build/ios-app.xcarchive -exportPath $PWD/build/ios-app.ipa -exportOptionsPlist ios-app/ExportOptions.plist
        working-directory: "./mobile"

      - name: Upload IPA Package
        uses: actions/upload-artifact@v4
        with:
          name: ipaPackage
          path: "mobile/build/xcode-frameworks/ios-app.ipa"
          retention-days: 1
          if-no-files-found: 'error'

  publish:
    needs: [build-android, build-ios]
    runs-on: ubuntu-latest
    steps:
      - name: Download APK Package
        uses: actions/download-artifact@v4
        with:
          name: apkPackage

      - name: Download IPA Package
        uses: actions/download-artifact@v4
        with:
          name: ipaPackage

      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Preview ${{ github.ref }}
          generate_release_notes: true
          prerelease: true
          draft: false

      - name: Rename packages
        run: |
          mv apkPackage/composeApp-debug.apk area-preview.apk
          mv ipaPackage/ios-app.ipa area-preview.ipa

      - name: Upload APK to Pre Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: .
          asset_name: "area-preview.apk"
          asset_content_type: application/vnd.android.package-archive

      - name: Upload IPA to Pre Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: .
          asset_name: "area-preview.ipa"
          asset_content_type: application/octet-stream

  check-tag:
    needs: [publish]
    if: ${{ github.event.action == 'push' && needs.publish.status != 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Delete tag
        run: |
          git tag -d ${{ github.ref }}
          git push origin --delete ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}