name: Mobile - Build Android Package
env:
  APK_NAME: "composeApp"
on:
  push:
    branches:
      - dev
      - mobile/dev
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Set Gradle properties
        run: |
          echo "org.gradle.jvmargs=-Xmx4096m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8" >> gradle.properties
        working-directory: "./mobile"

      - name: Run Android Unit Tests
        run: ./gradlew testDebugUnitTest
        working-directory: "./mobile"

      - name: Build APK
        run: ./gradlew assembleDebug
        working-directory: "./mobile"

      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ github.run_number }}.dev"
          release_name: Release Pre-Prod Android N°${{ github.run_number }}
          prerelease: 'false'
          draft: 'true'

      - name: Upload APK to Draft Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "./mobile/${{ env.APK_NAME }}/build/outputs/apk/debug/${{ env.APK_NAME }}-debug.apk"
          asset_name: "${{ env.APK_NAME }}-debug.apk"
          asset_content_type: application/vnd.android.package-archive
