name: Web - Deploy Preview
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  pull_request:
    types: [closed]
    branches:
      - dev
  push:
    branches:
      - dev
      - ci-cd/*

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apk update
          apk add bash curl nodejs npm

      - name: Using Vercel adapter i/o Node for SvelteKit app
        run: mv svelte.config.deploy.js svelte.config.js
        working-directory: "./web"

      - name: Install Vercel CLI
        run: |
          rm -rf package-lock.json
          npm install --global vercel@latest
        working-directory: "./web"

      - name: Link, Configure, Build and Deploy the Vercel Preview
        run: |
          vercel link --token=${{ secrets.VERCEL_TOKEN }} --yes --project=area-app
          vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
          vercel env pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }} .env
          sed -i.bak '/rootDirectory/d' .vercel/project.json
          vercel build --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: "./web"
