name: Web - Deploy Production
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apk update
          apk add bash curl nodejs npm wget

      - name: Using Vercel adapter i/o Node for SvelteKit app
        run: mv svelte.config.deploy.js svelte.config.js
        working-directory: "./web"

      - name: Install Vercel CLI
        run: |
          rm -rf package-lock.json
          npm install --global vercel@latest
        working-directory: "./web"

      - name: Link and Configure project
        run: |
          vercel link --token=${{ secrets.VERCEL_TOKEN }} --yes --project=area-app
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          vercel env pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }} .env
          sed -i.bak '/rootDirectory/d' .vercel/project.json
        working-directory: "./web"

      - name: Get latest release
        id: lts
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: RotClub
          repo: AREA

      - name: Download APK
        run: |
          mkdir mobile
          wget "https://github.com/RotClub/AREA/releases/download/${{ steps.lts.outputs.release }}/area-preview.apk"
          mv area-preview.apk mobile/client.apk
        working-directory: "./web/static/"

      - name: Build & Deploy the Vercel Preview
        run: |
          vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: "./web"
