name: Web - Check Syntax and run Tests
on:
  push:
    branches:
      - dev
      - web/*

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apk update
          apk add bash curl nodejs npm
          npm install
        working-directory: "./web"
      - name: Run ESLint
        run: npm run lint
        working-directory: "./web"
  testing:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apk update
          apk add bash curl nodejs npm
          npm install
        working-directory: "./web"
      - name: Run tests
        run: npm run test
        working-directory: "./web"
